project_id = "oztsymfskxaeonxqggfb"

[functions.locations-admin]
verify_jwt = false

[functions.events-admin]
verify_jwt = false

[functions.store-view]
verify_jwt = false

[functions.store-links-admin]
verify_jwt = false

[functions.store-articles-admin]
verify_jwt = false

[functions.mapbox-token]
verify_jwt = false

[functions.receipt-ocr]
verify_jwt = false
